### ISSUE TITLE
RegExp.compile("^[a-z][a-z0-9]*$", "i")  leads to NPE

### ISSUE THREAD

**Issue by treblereel** [gwtproject/gwt-regexp#2]
Error in console.log:
Uncaught TypeError: Cannot read property 'm_compile__java_lang_String__java_lang_String' of null

Thanks for any help !

**Comment by FrankHossfeld** [comment]
Tried to reproduce, but was not able. Can you provide more informations please.

**Comment by niloc132** [comment]
Closing this, looks like it could have been an early j2cl-maven-plugin error with dependencies not being present.
